version: "3"
services:
  # bootnode:
  #   hostname: bootnode
  #   container_name: bootnode
  #   build:
  #     context: ./bootnode 
  #   command: bootnode -nodekey /tmp/boot.key
  #   volumes:
  #     - ./nodes/boot.key:/tmp/boot.key
  #   ports:
  #     - 30303:30303/udp
  #     - 30301:30301/udp
  node_1:
    hostname: node_1
    image: ethereum/client-go
    command: --nousb --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key --port 30313 --http --http.addr "0.0.0.0"  --gasprice 0 --http.port 8502 --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid 1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    volumes:
      - ./nodes/node_1/keys/password:/root/files/password:ro
      - ./nodes/node_1/keys/priv.key:/root/files/priv.key:ro
      - ./nodes/node_1/data:/root/data:rw
    ports:
      - 30313:30313
      - 8502:8502
  node_2:
    hostname: node_2
    image: ethereum/client-go
    command: --nousb  --datadir /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key --port 30314 --http --http.addr "0.0.0.0"  --gasprice 0 --http.port 8503 --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid 1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    volumes:
      - ./nodes/node_2/keys/password:/root/files/password:ro
      - ./nodes/node_2/keys/priv.key:/root/files/priv.key:ro
      - ./nodes/node_2/data:/root/data:rw
    ports:
      - 30314:30314
      - 8503:8503
  # node_3:
  #   hostname: node_3
  #   image: ethereum/client-go
  #   command: --nousb --datadir /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key --port 30315 --http --http.addr "0.0.0.0" --gasprice 0 --http.port 8504 --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect --networkid 1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
  #   volumes:
  #     - ./nodes/node_3/keys/password:/root/files/password:ro
  #     - ./nodes/node_3/keys/priv.key:/root/files/priv.key:ro
  #     - ./nodes/node_3/data:/root/data:rw
  # node_4:
  #   hostname: node_4
  #   image: ethereum/client-go
  #   command:  --nousb --datadir /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key --port 30316 --http --http.addr "0.0.0.0"   --gasprice 0 --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect --networkid 13234  --allow-insecure-unlock --networkid 1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
  #   volumes:
  #     - ./nodes/node_4/keys/password:/root/files/password:ro
  #     - ./nodes/node_4/keys/priv.key:/root/files/priv.key:ro
  #     - ./nodes/node_4/data:/root/data:rw
